apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: service
  name: service
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    name: http
  selector:
    io.kompose.service: service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: service
  name: service
spec:
  selector:
    matchLabels:
      io.kompose.service: service
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: service
    spec:
      containers:
      - image: quinner/devops_tutorial
        name: service
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources: {}
        env:
          - name: MONGO_URI
            value: mongodb://mongo:27017
          - name: MONGODB_DATABASE
            value: flaskdb
          - name: MONGODB_USERNAME
            value: devops
          - name: MONGODB_PASSWORD
            value: devops_password
          - name: MONGODB_HOSTNAME
            value: mongodb
          - name: MONGODB_PORT
            value: '27017'
      restartPolicy: Always
status: {}